#!/bin/sh -e

# if we do not have debconf, we just skip this
. /usr/share/debconf/confmodule || exit 0

db_version 2.0
db_title opendwarf-config

db_fset opendwarf-config/gosaconffile seen false
db_input high opendwarf-config/gosaconffile || true
db_go || true
