#!/bin/sh -e
# Source debconf library.
. /usr/share/debconf/confmodule

db_version 2.0
db_title opendwarf-config

db_get opendwarf-config/gosaconffile
gosaconffile=$RET

echo $gosaconffile > /etc/opendwarf/gosa

